Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(f"The labels predicted are {sk_kmeans.labels_}.")
print(f"The inertia is {sk_kmeans.inertia_}.")
np.testing.assert_allclose(kmeans.inertia, sk_kmeans.inertia_, rtol=1e-1)
------------------

----- stdout -----
The labels predicted are [0 2 1 1 0 2 2 0 0 2 1 0 2 2 1 2 0 1 0 0 0 0 2 2 1 0 1 2 1 2 2 1 2 0 1 1 1
 1 1 2 2 1 0 1 0 1 0 2 0 1 2 0 2 0 2 1 0 0 2 0 2 1 1 0 0 2 1 1 1 1 2 1 1 1
 1 2 2 0 2 2 0 0 0 2 1 2 2 2 2 1 0 1 2 2 0 2 2 0 0 2 0 0 1 2 0 2 1 1 2 1 1
 2 0 0 2 1 0 0 2 0].
The inertia is 28.606767410476095.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[15], line 3[0m
[1;32m      1[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe labels predicted are [39m[38;5;132;01m{[39;00msk_kmeans[38;5;241m.[39mlabels_[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m)
[1;32m      2[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe inertia is [39m[38;5;132;01m{[39;00msk_kmeans[38;5;241m.[39minertia_[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m)
[0;32m----> 3[0m [43mnp[49m[38;5;241;43m.[39;49m[43mtesting[49m[38;5;241;43m.[39;49m[43massert_allclose[49m[43m([49m[43mkmeans[49m[38;5;241;43m.[39;49m[43minertia[49m[43m,[49m[43m [49m[43msk_kmeans[49m[38;5;241;43m.[39;49m[43minertia_[49m[43m,[49m[43m [49m[43mrtol[49m[38;5;241;43m=[39;49m[38;5;241;43m1e-1[39;49m[43m)[49m

    [0;31m[... skipping hidden 1 frame][0m

File [0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:79[0m, in [0;36mContextDecorator.__call__.<locals>.inner[0;34m(*args, **kwds)[0m
[1;32m     76[0m [38;5;129m@wraps[39m(func)
[1;32m     77[0m [38;5;28;01mdef[39;00m [38;5;21minner[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds):
[1;32m     78[0m     [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_recreate_cm():
[0;32m---> 79[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/testing/_private/utils.py:797[0m, in [0;36massert_array_compare[0;34m(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf, strict)[0m
[1;32m    793[0m         err_msg [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m [38;5;241m+[39m [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m.[39mjoin(remarks)
[1;32m    794[0m         msg [38;5;241m=[39m build_err_msg([ox, oy], err_msg,
[1;32m    795[0m                             verbose[38;5;241m=[39mverbose, header[38;5;241m=[39mheader,
[1;32m    796[0m                             names[38;5;241m=[39m([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m), precision[38;5;241m=[39mprecision)
[0;32m--> 797[0m         [38;5;28;01mraise[39;00m [38;5;167;01mAssertionError[39;00m(msg)
[1;32m    798[0m [38;5;28;01mexcept[39;00m [38;5;167;01mValueError[39;00m:
[1;32m    799[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtraceback[39;00m

[0;31mAssertionError[0m: 
Not equal to tolerance rtol=0.1, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 6.43176254
Max relative difference: 0.2248336
 x: array(35.03853)
 y: array(28.606767)

